insert into "GownType" (id, name) values
  (gen_random_uuid(), 'Ball Gown'),
  (gen_random_uuid(), 'Mermaid/Trumpet'),
  (gen_random_uuid(), 'A-Line'),
  (gen_random_uuid(), 'Bridgerton'),
  (gen_random_uuid(), 'Longtrain Prenup'),
  (gen_random_uuid(), 'With Train'),
  (gen_random_uuid(), 'Floor Length'),
  (gen_random_uuid(), 'Above Floor Length'),
  (gen_random_uuid(), 'Fitted/Bodycon/Body Hugging'),
  (gen_random_uuid(), 'Beaded/Sequin/Glitered/Glitz and Glam'),
  (gen_random_uuid(), 'High Slit'),
  (gen_random_uuid(), 'Sleeveless'),
  (gen_random_uuid(), 'With Sleeves'),
  (gen_random_uuid(), 'Fairy/Enchanted'),
  (gen_random_uuid(), 'Vintage'),
  (gen_random_uuid(), 'Gatsby'),
  (gen_random_uuid(), 'Lace'),
  (gen_random_uuid(), 'Coat/Barong'),
  (gen_random_uuid(), 'Filipiniana'),
  (gen_random_uuid(), 'Costume'),
  (gen_random_uuid(), 'Pastel');
  (gen_random_uuid(), 'Off-shoulder'),

insert into "GownSize" (id, label) values
  (gen_random_uuid(), 'XS'),
  (gen_random_uuid(), 'Small'),
  (gen_random_uuid(), 'Medium'),
  (gen_random_uuid(), 'Large'),
  (gen_random_uuid(), 'XL'),
  (gen_random_uuid(), '2XL'),
  (gen_random_uuid(), '3XL'),
  (gen_random_uuid(), '4XL'),
  (gen_random_uuid(), '5XL'),
  (gen_random_uuid(), 'kids');