name: Trigger Quarterly Supabase Report

on:
  schedule:
    - cron: "0 0 5 4,7,10,1 *" # At 00:00 on April 5, July 5, Oct 5, Jan 5
  workflow_dispatch: # Optional: lets you manually trigger from GitHub

jobs:
  call-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -i -X POST "https://rsqbegudzpexahrmtzqb.supabase.co/functions/v1/archive-quarterly-data" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
